use_frameworks!

target 'Reader' do
  pod 'EpubExtractor', :path => '../'
  pod 'FirebaseCore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'ReaderTests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
